version: "3"

services:
  docs:
    image: haproxy:2.9-alpine
    container_name: docs
    hostname: docs
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs-http.rule=Host(`docs.edgee.dev`)"
      - "traefik.http.routers.docs-http.entrypoints=web"
      - "traefik.http.routers.docs-http.service=docs-edgee-http"
      - "traefik.http.services.docs-edgee-http.loadbalancer.server.port=80"
      - "traefik.http.services.docs-edgee-http.loadbalancer.server.scheme=http"

      - "traefik.http.routers.docs-https.rule=Host(`docs.edgee.dev`)"
      - "traefik.http.routers.docs-https.entrypoints=websecure"
      - "traefik.http.routers.docs-https.service=docs-edgee-https"
      - "traefik.http.routers.docs-https.tls=true"
      - "traefik.http.services.docs-edgee-https.loadbalancer.server.port=80"
      - "traefik.http.services.docs-edgee-https.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.https-header.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.docs-https.middlewares=https-header"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - edgee

networks:
  edgee:
    driver: bridge
